# Generated by Django 5.0.6 on 2024-06-15 04:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Esporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('alterado_em', models.DateTimeField(auto_now=True)),
                ('descricao', models.CharField(max_length=50)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Campeonato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('alterado_em', models.DateTimeField(auto_now=True)),
                ('descricao', models.CharField(max_length=50)),
                ('regiao', models.CharField(max_length=50)),
                ('ano', models.IntegerField()),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('esporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aphonso_bet.esporte')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('alterado_em', models.DateTimeField(auto_now=True)),
                ('fatorCasa', models.FloatField(default=1)),
                ('fatorFora', models.FloatField(default=1)),
                ('dataEHora', models.DateTimeField()),
                ('local', models.CharField(max_length=100)),
                ('resultadoCasa', models.IntegerField(default=0)),
                ('resultadoFora', models.IntegerField(default=0)),
                ('finalizado', models.BooleanField(default=False)),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aphonso_bet.campeonato')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Aposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('alterado_em', models.DateTimeField(auto_now=True)),
                ('valor_aposta', models.FloatField()),
                ('total_premio', models.FloatField()),
                ('resultadoCasa', models.IntegerField(default=0)),
                ('resultadoFora', models.IntegerField(default=0)),
                ('quitado', models.BooleanField(default=False)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apostador', to=settings.AUTH_USER_MODEL)),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aphonso_bet.jogo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Moeda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('alterado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=50)),
                ('acronimo', models.CharField(max_length=3)),
                ('simbolo', models.CharField(max_length=2)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Carteira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('alterado_em', models.DateTimeField(auto_now=True)),
                ('saldo', models.FloatField(default=50.0)),
                ('banco', models.CharField(max_length=50, null=True)),
                ('agencia', models.IntegerField(null=True)),
                ('conta', models.CharField(max_length=50, null=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proprietario', to=settings.AUTH_USER_MODEL)),
                ('moeda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aphonso_bet.moeda')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MovimentacoesFinanceiras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('alterado_em', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('EN', 'Entradas'), ('SA', 'Saídas'), ('TR', 'Transferências')], default='EN', max_length=2)),
                ('valor', models.FloatField()),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinatario', to='aphonso_bet.carteira')),
                ('moeda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aphonso_bet.moeda')),
                ('remetente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remetente', to='aphonso_bet.carteira')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('alterado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=50)),
                ('bandeira', models.ImageField(upload_to='upload')),
                ('acronimo', models.CharField(max_length=3)),
                ('pais', models.CharField(default='BRASIL', max_length=50)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('esporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aphonso_bet.esporte')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='jogo',
            name='timeCasa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casa', to='aphonso_bet.time'),
        ),
        migrations.AddField(
            model_name='jogo',
            name='timeFora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fora', to='aphonso_bet.time'),
        ),
        migrations.CreateModel(
            name='CampeonatoTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('alterado_em', models.DateTimeField(auto_now=True)),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aphonso_bet.campeonato')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aphonso_bet.time')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
